[project]
org-name= "hsdg"
version= "0.1.1"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["jms"]
repository = "https://github.com/hsdg-integration/module-ballerina-java.jms"

[dependencies]

[platform]
target = "java8"

[[platform.libraries]]
module = "jms"
path = "libs/javax.jms-api-2.0.1.jar"
artifactId = "javax.jms-api"
version = "2.0.1"
groupId = "javax.jms"
