[project]
org-name= "hsdg"
version= "0.1.1"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["jms"]
repository = "https://github.com/hsdg-integration/module-ballerina-java.jms"

[dependencies]

[platform]
target = "java8"

[[platform.libraries]]
module = "jms"
path = "../utils/target/jms-utils-0.0.1.jar"
artifactId = "jms-utils"
version = "0.8.1"
groupId = "hsdg"

[[platform.libraries]]
module = "jms"
path = "../utils/target/classes/lib/javax.jms-api-2.0.1.jar"
artifactId = "javax.jms-api"
version = "2.0.1"
groupId = "javax.jms"
