name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile Java Dependencies
        run: |
          cd utils
          mvn install
      - name: Build Ballerina Module
        run: |
          cd jms
          ballerina build -c -a