name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: installing ballerina 1.2.9
        run: |
          wget https://dist.ballerina.io/downloads/1.2.9/ballerina-linux-installer-x64-1.2.9.deb
          sudo dpkg -i ballerina-linux-installer-x64-1.2.9.deb
      - name: Compile Java Dependencies
        run: |
          cd utils
          mvn install
          cd ..
      - name: Build Ballerina Module
        run: |
          cd jms
          ballerina build -c -a
          cd ..