name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: installing ballerina
        run: |
          wget https://dist.ballerina.io/downloads/1.2.11/ballerina-linux-installer-x64-1.2.11.deb
          sudo dpkg -i ballerina-linux-installer-x64-1.2.11.deb
      - name: Build Ballerina Module
        run: |
          cd jms
          ballerina build -c -a
          ballerina push -a
          cd ..
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL }}